esphome:
  name: ipv4
  platform: ESP8266
  board: d1_mini_pro
  # arduino_version: 2.5.2

wifi:
  ssid: suxnet1
  password: !secret wifipwd
  ap:
    ssid: "fallback"
    password: "fallbackpwd"
#    ap_timeout: 15s
    manual_ip:
      #static_ip: 192.168.10.1
      static_ip: 2001:470:28:879::34b 
      gateway: 192.168.10.1
      subnet: 255.255.255.0

captive_portal:

debug:

logger:
  level: VERY_VERBOSE

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

api:

#web_server:
#  port: 80
#mqtt:
#  broker: 192.168.20.20
