esphome:
  name: ipv4idf

# Example configuration entry
esp32:
  board: esp32dev
  framework:
    type: esp-idf
      # version: 4.3.0
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

wifi:
  ssid: suxnet1
  password: !secret wifipwd
  ap: {}
#    ssid: "fallback"
#    password: "fallbackpwd"
#    # ap_timeout: 5s
#    manual_ip:
#      static_ip: 192.168.10.1
#      gateway: 192.168.10.1
#      subnet: 255.255.255.0

network:
  enable_ipv6: false

debug:

logger:
  level: VERY_VERBOSE

#web_server:
#  port: 80

api:
