esphome:
  name: ipv632

esp32:
  board: esp32dev
  framework:
    type: arduino
      # version: dev
    # platform_version: 3.0.0
    # version: 2.0.0
    # platform_version: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream


wifi:
  ssid: suxnet
  password: !secret wifipwd

network:
  enable_ipv6: true

debug:

logger:
  level: VERY_VERBOSE

web_server:
  port: 80

mqtt:
#  broker: time1.linuxguru.se
  broker: 2001:470:28:879::34b 
